odom_frame: odom            # Defaults to "odom" if unspecified
base_link_frame: base_link  # Defaults to "base_link" if unspecified
world_frame: odom           # Defaults to the value of odom_frame if unspecified

debug: true
debug_out_file: ~/rob_loc_debug.txt

two_d_mode: true

frequency: 50

odom0: odom
odom0_config: [true,  true,  false,
               false, false, true,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: true
odom0_queue_size: 10

pose0: /jfr/robot/correction
pose0_config: [true,  true,  false,
               false, false, true,
               false, false, false,
               false, false, true,
               false, false, false]
z_differential: false
odom0_queue_size: 10

odom1: gps/rtkfix
odom1_config: [true, true, false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom1_differential: false
odom1_queue_size: 2

odom2: odom/lidarcov1
odom2_config: [true,  true,  false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom2_differential: false
odom2_queue_size: 10

odom3: odom/target1
odom3_config: [true,  true,  false,
               false, false, false,
               true, true, false,
               false, false, false,
               false, false, false]
odom3_differential: false
odom3_queue_size: 10

imu0: imu/data
imu0_config: [false, false, false,
              false, false, true,
              true, true, false,
              false, false, true,
              true, true,  false]
imu0_differential: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true


