odom_frame: target            # Defaults to "odom" if unspecified
base_link_frame: base_link  # Defaults to "base_link" if unspecified
world_frame: target           # Defaults to the value of odom_frame if unspecified

debug: true
debug_out_file: /home/ugv/rob_loc_debug.txt

two_d_mode: true

frequency: 50

odom0: odom/lidar
odom0_config: [true,  true,  false,
               false, false, false,
               true,  true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10

odom1: odom/camc
odom1_config: [true, true, false,
               false, false, false,
               true,  true, false,
               false, false, false,
               false, false, false]
odom1_differential: false
odom1_queue_size: 2

odom2: odom/camg
odom2_config: [true,  true,  false,
               false, false, false,
               true,  true, false,
               false, false, false,
               false, false, false]
odom2_differential: false
odom2_queue_size: 10

